spring.application.name=ambientes

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html

app.secret=${SECRET:SECRET}

spring.profiles.active=${APP_PROFILE:test}