spring.config.import=optional:file:.env[.properties]

spring.application.name=ambientes

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.jackson.deserialization.fail-on-unknown-properties=false
spring.mvc.pathmatch.use-suffix-pattern=false

springdoc.swagger-ui.path=/swagger-ui.html

app.secret=${SECRET}
api.server.url=${API_SERVER_URL:http://localhost:8080}

cors.origins=${CORS_ORIGINS}

spring.profiles.active=${APP_PROFILE}